language: go

sudo: false

go:
  - 1.6

script:
  - mkdir build
  - cd build
  - go build ../api/api.go
  - go build ../service/service.go

after_success:
  - cp ../config.yml ./
  - zip artifacts.zip ./*

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CYY88p4X1SZxpJieWAeThsi6skufmm+NrRb4y3FYwh8Y1f9LqzpBiudC/YF//0c6PoPo0Kw4DuIahWngSUInqBleQejCuO5R2vsH6c/GFaLNQiyPJubYhgBSng0RIkfEG5YLxrMEWk/YDxrsmvnH9RVrheFDx3ty7hIFnoT/kPqExbRFSRRGGKj8XTr+xcZH2CN7Lzb9nLZcABDhE2etk6ekFLIFbTxGmM5p0QB9JTakB1IDRW99D8tz1d0e1SuyZWlfzUv56IvDLouqW4OfhKoip5R0Xd0kOO4vvL7/FI1EHJbbzt2elNaDE4vcrSLNET/LPaU8QSZBm7gXvwTMgnMilusXWGcuhptLTautpZkMeF/oNRxEDjRoxcwqz85XDu5vbAZisbJDtEnSgQPbf2YlCGHftmFTMWNnWLzufUCd4vaKRRc616aLERusP6fuL0FJHkkwlIxOZj8NkknsZZNI7wRrL1mqlPu4aYxj+npy9YXf2mi0+g23wJXe6bb5XhXPSRHk3iiKc2Nf7BKermnEeBe57uRNVMKR0/IvLP8G+DsTnQ5zKtjrgf/vEDn6dTZirEIi32yrbcbcbU5p2GdSU0bVLCgkUDYXZDSYJ95SBN0QtdEKT3fXWGiOe8XafYoHcEOL5rKIAzACUq/9LYqJXpbPXhMn1jTR729pCgY=
  file: build/artifacts.zip
  on:
    tags: true
