api:
  ip: 127.0.0.1
  port: 1337
  secret: "pleasechange"
  unixsocket: "./service_client.sock"

service:
  unixsocket: "./service.sock"

deployments:
- name: mydeploy1
  secret: deploy1secret
  description: "My test deploy service 1"
  user: root
  script:
  - echo "Hello World from mydeploy1"
  - whoami

- name: mydeploy2
  secret: deploy2secret
  description: "My test deploy service 2"
  user: vm
  script:
  - echo "Hello World from mydeploy2"
  - whoami
